interfaces:
  hundredGigE 1/1:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/1/1:
    description: "MOCINFRA-CTRL-U36-R"
    state: "up"
    untagged: 127
    tagged:
      - 911
      - 912
      - 913
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/1/2:
    description: "MOCINFRA-CTRL-U35-R"
    state: "up"
    untagged: 127
    tagged:
      - 911
      - 912
      - 913
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/1/3:
    description: "MOCINFRA-CTRL-U34-R"
    state: "up"
    untagged: 127
    tagged:
      - 911
      - 912
      - 913
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/1/4:
    state: "down"
  hundredGigE 1/2:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/2/1:
    description: "ESI-CTRL-U33-R Overcloud 0"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/2/2:
    description: "ESI-CTRL-U32-R Overcloud 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/2/3:
    description: "ESI-CTRL-U31-R Overcloud 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/2/4:
    state: "down"
  hundredGigE 1/3:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/3/1:
    description: "ESI Undercloud Port 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 208
    tagged:
      - 623
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/3/2:
    state: "up"
    description: "MOC-FW-1 Port 4"
    mtu: 9216
  TenGigabitEthernet 1/3/3:
    state: "down"
  TenGigabitEthernet 1/3/4:
    state: "down"
  hundredGigE 1/4:
    description: "NESE: MGHPCC-RC-NESE-7-B-12 GW2 Port 8 (cabinet 7-B-12)"
    state: "up"
    mtu: 9216
    ip4: "10.255.215.69/26"
    ip6: "2607:fb60:2406:2::69/64"
  hundredGigE 1/5:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/5/1:
    description: "MOC-FW-11 Port 3"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/5/2:
    description: "MOC-FW-11 Port 4"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/5/3:
    description: "MOC-FW-12 Port 3"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/5/4:
    description: "MOC-FW-12 Port 4"
    state: "up"
    mtu: 9216
  hundredGigE 1/6:
    state: "down"
  hundredGigE 1/7:
    state: "down"
  hundredGigE 1/8:
    state: "down"
  hundredGigE 1/9:
    description: "Uplink to R8-PA-C23"
    state: "up"
    mtu: 9216
  hundredGigE 1/10:
    state: "down"
  hundredGigE 1/11:
    description: "UNITY-NESE-SW"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged:
      - 300
    stp:
      disabled: true
  hundredGigE 1/12:
    state: "down"
  hundredGigE 1/13:
    state: "down"
  hundredGigE 1/14:
    state: "down"
  hundredGigE 1/15:
    state: "down"
  hundredGigE 1/16:
    state: "down"
  hundredGigE 1/17:
    state: "down"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    description: "NERC-CORE-2 Port 36"
    state: "up"
    mtu: 9216
    autoneg: false
    fec: false
  hundredGigE 1/22:
    description: "NERC-CORE-1 Port 36"
    state: "up"
    mtu: 9216
    autoneg: false
    fec: false
  hundredGigE 1/23:
    state: "down"
  hundredGigE 1/24:
    state: "down"
  hundredGigE 1/25:
    state: "down"
  hundredGigE 1/26:
    description: "OCT-CORE-2 Port 26"
    state: "up"
    mtu: 9216
  hundredGigE 1/27:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/27/1:
    description: "MOC Cisco ####"
    state: "up"
    mtu: 9216
  hundredGigE 1/28:
    state: "down"
  hundredGigE 1/29:
    description: "MOC-CORE-4 Port 29"
    state: "up"
    mtu: 9216
  hundredGigE 1/30:
    description: "MOC-CORE-3 Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/31:
    description: "MOC-CORE-1 Port 31 VLT"
    state: "up"
  hundredGigE 1/32:
    description: "MOC-CORE-1 Port 32 VLT"
    state: "up"
  TenGigabitEthernet 1/33:
    description: "MOC-MCORE-1 Port 50"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/34:
    description: "CSAIL Uplink"
    state: "up"
  Port-channel 10:
    description: "MOC Core Link to CORE-3 and CORE-4"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/29"
      - "hundredGigE 1/30"
    mlag: "Port-channel 10"
  Port-channel 11:
    description: "MOC Cisco LAG"
    state: "up"
    mtu: 9216
    tagged: "all"
    portmode: "trunk"
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/27/1"
    mlag: "Port-channel 11"
    stp:
      disabled: true
      rootguard: true
  Port-channel 20:
    description: "Link to OCT-CORE-1 and OCT-CORE-2"
    state: "up"
    portmode: "trunk"
    tagged:
      - 10
      - 127
      - 204
      - 208
      - 211
      - 213
      - 250
      - 351:499
      - 501:622
      - 623
      - 624:630
      - 911
      - 931
      - 935
      - 2076
      - 2305:2308
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/26"
    mlag: "Port-channel 20"
    stp:
      disabled: true
      rootguard: true
  Port-channel 40:
    description: "R8PAC23-Uplink"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/9"
    mlag: "Port-channel 40"
    stp:
      rootguard: true
  Port-channel 50:
    description: "NERC core LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 204
      - 211
      - 300
      - 350
      - 351:499
      - 501:622
      - 623
      - 624:630
      - 911
      - 930
      - 935
      - 2076
      - 2141:2148
      - 2170
      - 2172:2177
      - 2180
      - 2303:2308
    mtu: 9216
    stp:
      disabled: true
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/21"
      - "hundredGigE 1/22"
    mlag: "Port-channel 50"
  Port-channel 100:
    description: "MOC-CORE-1 VLT LAG"
    state: "up"
    mtu: 9216
    lag-members:
      - "hundredGigE 1/31"
      - "hundredGigE 1/32"
  Port-channel 101:
    description: "MOC-MCORE-1 Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/33"
    mlag: "Port-channel 101"
    stp:
      rootguard: true
  Port-channel 102:
    description: "CSAIL LAG"
    state: "up"
    portmode: "hybrid"
    untagged: 10
    tagged:
      # CSAIL
      - 3801
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/34"
    mlag: "Port-channel 102"
    stp:
      disabled: true
      rootguard: true
  Port-channel 200:
    description: "MOC-FW-1 LAG"
    state: "up"
    portmode: "trunk"
    mtu: 9216
    tagged:
      - 127
      - 201
      - 204
      - 277
      - 911
      - 930
      - 931
      - 2076
      - 2303:2308
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/3/2"
    mlag: "Port-channel 200"
  Port-channel 201:
    description: "MOC-FW-11 LAG"
    state: "up"
    portmode: "trunk"
    mtu: 9216
    tagged:
      - 127
      - 201
      - 204
      - 211
      - 277
      #- 911
      - 912
      - 913
      - 930
      - 931
      - 935
      - 2076
      - 2303:2308
      - 3801
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/5/1"
    mlag: "Port-channel 201"
  Port-channel 202:
    description: "MOC-FW-12 LAG"
    state: "up"
    portmode: "trunk"
    mtu: 9216
    tagged:
      - 127
      - 201
      - 204
      - 211
      - 277
      #- 911
      - 912
      - 913
      - 930
      - 931
      - 935
      - 2076
      - 2303:2308
      - 3801
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/5/2"
    mlag: "Port-channel 202"
  Vlan 211:
    state: "up"
    ip4: "10.0.120.3/22"
    mtu: 9216
  Vlan 930:
    state: "up"
    ip4: "10.80.1.2/20"
  Vlan 935:
    state: "up"
    ip4: "10.82.1.2/20"
  Vlan 2076:
    state: "up"
    ip4: "10.85.0.3/22"
  Vlan 2176:
    state: "up"
    ip4: "10.30.9.102/24"
